FROM node:10.14.1-alpine

WORKDIR /nuxt

# RUN apk update && \
#     apk add --update git && \
#     apk add --update nodejs && \
#     apk add --update npm && \
#     apk add --update yarn && \
#     rm -rf /var/cache/apk/*

# RUN yarn install

# CMD yarn run dev