version: 0.0
os: linux
files:
    - source: /client
      destination: /home/ec2-user
    - source: /server
      destination: /home/ec2-user
    - source: /.docker
      destination: /home/ec2-user
# hooks:
#   BeforeInstall:
#     - location: scripts/install_dependencies
#       timeout: 300
#       runas: root
#     - location: scripts/start_server
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server
#       timeout: 300
#       runas: root