version: "3"

services:
  golang:
    build:
      context: ./
      dockerfile: .docker/golang/Dockerfile
    volumes:
      - ./server:/go/src
    ports:
      - "8080:8080"
    tty: true
  nuxt:
    build:
      context: ./
      dockerfile: .docker/nuxt/Dockerfile
    volumes:
      - ./client:/nuxt
    ports:
      - "3000:3000"
    tty: true
  mysql:
    image: mysql:latest
    container_name: go_db
    volumes:
      - ./.mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    container_name: mysql-container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - "8081:80"
    volumes: 
      - /sessions